<?php
$relationships = array (
    'new_brands_modified_user' =>
        array (
            'id' => 'd60b6522-0438-4d6e-87b1-67bc56c3e7e2',
            'relationship_name' => 'new_brands_modified_user',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'new_Brands',
            'rhs_table' => 'new_brands',
            'rhs_key' => 'modified_user_id',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => NULL,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => true,
        ),
    'new_brands_created_by' =>
        array (
            'id' => 'd74471af-c815-f78a-31f2-67bc5626a958',
            'relationship_name' => 'new_brands_created_by',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'new_Brands',
            'rhs_table' => 'new_brands',
            'rhs_key' => 'created_by',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => NULL,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => true,
        ),
    'new_brands_assigned_user' =>
        array (
            'id' => 'd7ef2e05-b8aa-4b41-e311-67bc5617e148',
            'relationship_name' => 'new_brands_assigned_user',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'new_Brands',
            'rhs_table' => 'new_brands',
            'rhs_key' => 'assigned_user_id',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => NULL,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => true,
        ),
    'securitygroups_new_brands' =>
        array (
            'id' => 'd926b578-43bf-7519-d6c2-67bc56e99875',
            'relationship_name' => 'securitygroups_new_brands',
            'lhs_module' => 'SecurityGroups',
            'lhs_table' => 'securitygroups',
            'lhs_key' => 'id',
            'rhs_module' => 'new_Brands',
            'rhs_table' => 'new_brands',
            'rhs_key' => 'id',
            'join_table' => 'securitygroups_records',
            'join_key_lhs' => 'securitygroup_id',
            'join_key_rhs' => 'record_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => 'module',
            'relationship_role_column_value' => 'new_Brands',
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => true,
        ),
    'new_brands_opportunities_1' =>
        array (
            'rhs_label' => 'Opportunities',
            'lhs_label' => 'Brands',
            'lhs_subpanel' => 'default',
            'rhs_subpanel' => 'default',
            'lhs_module' => 'new_Brands',
            'rhs_module' => 'Opportunities',
            'relationship_type' => 'many-to-many',
            'readonly' => true,
            'deleted' => false,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => true,
            'relationship_name' => 'new_brands_opportunities_1',
        ),
);